# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: سایت شخصی حسین زعفرانی
name: حسین زعفرانی
email: zaaferani@hotmail.com
description: >
  توضیحات سایت 
about: > # this means to ignore newlines until "baseurl:"
  حسین زعفرانی هستم
  در این مکان توضیحاتی در مورد خودم خواهم نوشت
#url: http://hossein-zaaferani.ir # the base hostname & protocol for your site
base_url: http://hossein-zaaferani.ir
blog: http://hossein-zaaferani.ir/blog

#base_url: http://127.0.0.1:4000
#blog: http://127.0.0.1:4000/blog
domain: hossein-zaaferani.ir
github_username: hos3ein
#google_plus_username: '#'
#twitter_username: '#'
#facebook_username: '#'
#instagram_username: '#'

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
timezone: Asia/Tehran
permalink: /blog/:categories/:year-:month-:day/:title
paginate: 3
paginate_path: "/blog/page:num/"

gems: [jekyll-paginate, jalalidate]