# Site settings
title: سایت شخصی حسین زعفرانی
name: حسین زعفرانی
email: zaaferani@hotmail.com
biography: >
  حسین زعفرانی متولد 13 بهمن 1374 در شهر قاین
  <br>
  دارای آشنایی با زبان های برنامه نویسی
  <br>
  Android, Basic4android, Python, C++, Html, Css, JavaScript, JQuery
  <br><br>
  <b>رزومه کاری</b>
  <br>
  ساخت نرم افزار شارژ حساب اینترنت برای دانشگاه بزرگمهر قاینات
  <br>
  ساخت چندین برنامه اندروید و انتشار آن ها در مارکت های معتبر
  <br>

base_url: http://hossein-zaaferani.ir
blog: http://hossein-zaaferani.ir/blog

#base_url: http://127.0.0.1:4000
#blog: http://127.0.0.1:4000/blog
domain: hossein-zaaferani.ir
github_username: hos3ein
#google_plus_username: '#'
#twitter_username: '#'
#facebook_username: '#'
#instagram_username: '#'

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
timezone: Asia/Tehran
#permalink: /blog/:categories/:year-:month-:day/:title
permalink: /blog/:title
paginate: 3
paginate_path: "/blog/page:num/"

gems: [jekyll-paginate, jalalidate]